services:
  #Create a service named "mysql_db" from the image "mariadb:latest"
  enset-discovery-service:
    build: ./discovery-service
    container_name: enset-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4

  mysql_db_resource:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    container_name: mysql_db_resource
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: resource-db #Database name
      MYSQL_USER: mahfoud #Database user
      MYSQL_PASSWORD: 1234 #Database password
    volumes:
      - mysql_data1:/var/lib/mysql1
    restart:
      always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3

  mysql_db_reservation:
    image: mariadb:10.6
    ports:
      - "3307:3307"
    container_name: mysql_db_reservation
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation-db #Database name
      MYSQL_USER: mahfoud #Database user
      MYSQL_PASSWORD: 1234 #Database password
    volumes:
      - mysql_data2:/var/lib/mysql2
    restart:
      always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
  #-----------------------------------------------------------------
  #Create a service named "phpmyadmin_db" from the image "phpmyadmin"
  phpmyadmin_db_resource:
    image: phpmyadmin:5.0
    ports:
      - "81:81"
    environment:
      PMA_HOST: mysql_db_resource
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: 1234
    container_name: phpmyadminresource
    depends_on:
      - mysql_db_resource
    restart:
      always
  phpmyadmin_db_reservation:
    image: phpmyadmin:5.0
    ports:
      - "82:82"
    environment:
      PMA_HOST: mysql_db_reservation
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: 1234
    container_name: phpmyadminreservation
    depends_on:
      - mysql_db_reservation
    restart:
      always

  enset-resources-service:
    build: ./resources-service
    container_name: enset-resources-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    restart: always
    depends_on:
      mysql_db_resource:
        condition: service_healthy

    environment:
      - DISCOVERY_SERVICE_URL=http://enset-discovery-service:8761/eureka
      - DB_URL=jdbc:mysql://mysql_db:3306/resource-db


  enset-reservations-service:
    build: ./reservation-service
    container_name: enset-reservations-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    restart: always
    depends_on:
      mysql_db_reservation:
        condition: service_healthy
      enset-resources-service:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-discovery-service:8761/eureka
      - DB_URL=jdbc:mysql://mysql_db:3307/reservation-db

  enset-gateway-service:
    build: ./gateway-service
    container_name: enset-gateway-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-discovery-service:8761/eureka

  postgres-service:
    image: postgres
    container_name: postgres-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: k1234
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: "exit 0"
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sanaa@gmail.com
      PGADMIN_DEFAULT_PASSWORD: azer
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-service:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: k1234
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      postgres-service:
        condition: service_healthy
  angular-front:
    build: ./Angular-Front-App
    container_name: angular-front
    ports:
      - '8085:80'
    expose:
      - '8085'
    restart: always



volumes:
  mysql_data1:
  mysql_data2:
  postgres_data:
  pgadmin_data:
